site_name: LINC Documentation
repo_name: "lincbrain/linc-docs"
repo_url: "https://github.com/lincbrain/linc-docs"
copyright: "CC-BY 4.0"
use_directory_urls: true
site_url: https://docs.lincbrain.org

# Material theme
theme:
  name: "material"
  language: "en"
  favicon: img/linc.logo.color+white.notext+square.png
  logo: img/linc.logo.color+black.alpha.notext.png
  palette:
    - scheme: default
      toggle: 
        icon: material/weather-night
        name: Dark mode
      primary: "deep purple"
      accent: "purple"
    - scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Light mode
      primary: "deep purple"
      accent: "purple"
  features:
    - toc.integrate

# Pages
nav:
  - Welcome: "index.md"
  - Upload data: "upload.md"
  - Dashboard: "dashboard.md"
  - LINC Convert: https://convert.lincbrain.org
  - Visualize data in Neuroglancer: "neuroglancer.md"
  - Webknossos:
    - Add Webknossos dataset: "webknossos-add-dataset.md"
    - Export Webknossos annotation: "webknossos-export-annotation.md"
    - Deployment: "webknossos-deployment.md"
    - Development: "webknossos-development.md"
  - Engaging Cluster: "engaging.md"
  - JupyterHub: "jupyterhub.md"
  - DANDI Docs: https://docs.dandiarchive.org
  - DANDI Client: https://dandi.readthedocs.io
  - Data:
    - HiP-CT: "data/hipct.md"
  - Design Docs:
    - Visualize private S3 assets with Neuroglancer: "neuroglancer-private-assets.md"
  - Health status: https://status.lincbrain.org
  - Contribute documentation: "contribute.md"
  - About this doc: "about.md"

# List of extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# List of plugins
plugins:
  - search
  - open-in-new-tab

# Customize theme
extra:
  generator: false
  analytics:
    provider: google
    property: G-E0ERHE0JXE
  social:
    - icon: material/home
      link: https://connects.mgh.harvard.edu/
      name: Homepage
    - icon: fontawesome/brands/slack
      link: https://mit-lincbrain.slack.com/
      name: Slack
    - icon: fontawesome/brands/github
      link: https://github.com/lincbrain
      name: GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/lincbrain
      name: Docker Hub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/lincbrain-cli
      name: PyPI

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
