site_name: LINC Documentation
repo_name: "lincbrain/linc-docs"
repo_url: "https://github.com/lincbrain/linc-docs"
copyright: "CC-BY 4.0"
use_directory_urls: true
site_url: https://docs.lincbrain.org

# Material theme
theme:
  name: "material"
  language: "en"
  favicon: img/linc.logo.color+white.notext+square.png
  logo: img/linc.logo.color+black.alpha.notext.png
  palette:
    - scheme: default
      toggle: 
        icon: material/weather-night
        name: Dark mode
      primary: "deep purple"
      accent: "purple"
    - scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Light mode
      primary: "deep purple"
      accent: "purple"
  features:
    - toc.integrate

# Pages
nav:
  - Welcome: "index.md"
  - Upload data: "upload.md"
  - Visualize data in Neuroglancer: "neuroglancer.md"
  - Webknossos:
    - Add Webknossos dataset: "webknossos-add-dataset.md"
    - Deployment: https://github.com/lincbrain/webknossos/blob/ak-dev/LINC_DEPLOYMENT.md
    - Development: https://github.com/lincbrain/webknossos/blob/ak-dev/LINC_DEVELOPMENT.md
  - Engaging Cluster: "engaging.md"
  - DANDI Docs: https://docs.dandiarchive.org
  - API:
    - DANDI Client: https://dandi.readthedocs.io
  - Contribute documentation: "contribute.md"
  - About this doc: "about.md"

# List of extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - toc:
      permalink: True

# List of plugins
plugins:
  - search
  - open-in-new-tab

# Customize theme
extra:
  generator: false
  analytics:
    provider: google
    property: G-E0ERHE0JXE
  social:
    - icon: material/home
      link: https://connects.mgh.harvard.edu/
      name: Homepage
    - icon: fontawesome/brands/slack
      link: https://mit-lincbrain.slack.com/
      name: Slack
    - icon: fontawesome/brands/github
      link: https://github.com/lincbrain
      name: GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/lincbrain
      name: Docker Hub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/lincbrain-cli
      name: PyPI